name: fraudstream_lakehouse
version: 1.0.0
config-version: 2

profile: fraudstream_lakehouse

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
  - target
  - dbt_packages

models:
  fraudstream_lakehouse:
    +materialized: view
    silver:
      +schema: silver
    gold:
      +schema: gold
